### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by chhh** [smacke/jaydio#1]
Hi, I know it's been 4 years since last commit here, so you probably don't maintain it anymore.
What would it take to add Windows support? Maybe you could give some directions, where to start digging?

**Comment by smacke** [comment]
Hi @chhh, yes I don't actively maintain this project anymore. I'm not familiar with windows system calls, but a brief search suggests that you'll want to hook up up Windows `CreateFile` via JNA (see [DirectIoLib.java](https://github.com/smacke/jaydio/blob/master/src/main/java/net/smacke/jaydio/DirectIoLib.java) for an example).

Reference: https://stackoverflow.com/questions/15971746/posix-o-direct-vs-windows-file-flag-write-through-file-flag-no-buffering
