### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by eolivelli** [smacke/jaydio#2]
Hi,
is this project still active ?
Are you planning to publish your project to Maven central ?

**Comment by smacke** [comment]
Hi @eolivelli, I'm not actively developing this project. I believe [it should be on Maven central already](https://mvnrepository.com/artifact/net.smacke/jaydio/0.1) (please also see README.md for what to add to pom.xml). Let me know if it doesn't work and I'll take a look, for now I'll go ahead and close this issue.

**Comment by eolivelli** [comment]
@smake 
thank you
I didn't find it.

**Comment by smacke** [comment]
@eolivelli, did you add the dependency as described in [README.md](https://github.com/smacke/jaydio/blob/master/README.md)? It is listed as:

```
<dependency>
    <groupId>net.smacke</groupId>
    <artifactId>jaydio</artifactId>
    <version>0.1</version>
</dependency>
```

As far as I know, adding this dependency to your pom.xml should be all you need to get the dependency from Maven central -- it works for me. Where specifically are you having trouble?

**Comment by eolivelli** [comment]
Sorry
The artifact is on Maven Central
https://mvnrepository.com/artifact/net.smacke/jaydio/0.1

Yesterday I was looking for the wrong groupId 

Thank you for checking again.
You library will be useful in my project (https://github/diennea/herddb) in order to leverage O_DIRECT with JDK8.

Now with JDK10+ O_DIRECT is natively available in the JDK10 and it is working very well.
