### ISSUE TITLE
Migrate off log4j 1.x

### ISSUE THREAD

**Issue by pmezrin0** [smacke/jaydio#5]
Hi, thank you for your efforts for maintaining the project!

Since that jaydio has dependency on log4j 1.x which has a public security vulnerability https://app.snyk.io/vuln/SNYK-JAVA-LOG4J-572732, and according to https://logging.apache.org/log4j/2.x/security.html it won't be fixed in log4j 1.x.

Would it be possible to migrate off log4j to other logging library? (e.g. just using slf4j-api and users can use [any of available implementation binding for their taste](http://www.slf4j.org/manual.html#swapping) such as [logback](http://logback.qos.ch/reasonsToSwitch.html)). 
If needed, I can create a PR for that.

cc: @smacke, What do you think about it?

Best Regards,
Pavel

**Comment by smacke** [comment]
I'd of course be happy to take a PR for this -- admittedly, I haven't looked at this library for a while. Do people still use maven?

**Comment by pmezrin0** [comment]
As far as I know, a lot of people still use maven, but gradle is also very popular nowadays for java projects.
Created PR: https://github.com/smacke/jaydio/pull/6
